### ISSUE TITLE
Registration Fee Error on Areas > 0

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#172]
The registration fee validation fails when sending an area > 0 via Voyager and the frontend, despite functioning correctly in tests.

Steps to Reproduce:
Submit a land registration with an area > 0 from Voyager or the frontend.

Expected Behavior: The transaction should proceed successfully when the area is valid.

Actual Behavior: The transaction fails.

Suggested Solution: Investigate and fix inconsistencies between the testing environment and Voyager/frontend behavior.

**Comment by GoSTEAN** [comment]
### Background 
 am a smart contract developer with hands-on experience in writing and deploying decentralized applications (dApps). I specialize in using Cairo, the programming language for StarkNet, to develop scalable and efficient smart contracts. 
 ### Steps
1. Check the smart contract logic to ensure area > 0 validation works the same in tests and on-chain.
2. Compare test and deployment environments to identify any configuration differences that might cause the issue.
3. Verify data sent from Voyager and frontend to ensure the correct area value is passed to the contract.
4. Manually test the registration with various area values in Voyager and frontend to reproduce the issue.
5. Fix inconsistencies and ensure the frontend and contract handle area values correctly, then test again to confirm the issue is resolved.
can I work on issue #172
