### ISSUE TITLE
Update Footer and Community Links and Implement Dark Mode on Landing Page

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#92]
1. Reposition "Powered by Starknet" and Update Community Links
Description: Move the "Powered by Starknet" element from the hero section to the footer. Replace it with the text "Onchain land, decentralized and secured." Additionally, include the Telegram link in the community links and create a dedicated "Guides" page. 

2.  Provide users with the option to switch between light and dark mode on the landing page. This will enhance user experience and accommodate different preferences. 
 

Definition of Completion: A toggle or button is available on the landing page to switch between light and dark mode. The page's appearance adjusts accordingly, ensuring readability and visual comfort in various lighting conditions.

Ref:

https://landver.vercel.app/

https://github.com/NoshonNetworks/landver/tree/main/frontend/landing_page

**Comment by NueloSE** [comment]
@fishonamos kindly assign me the above task 

To fix this issue, I'll follow these steps:

- Move "Powered by Starknet" to the Footer:
I'll locate the HTML or JSX code for the "Powered by Starknet" text in the hero section of the landing page. Then, I'll cut that corresponding code and paste it into the footer section, making sure to maintain the styling or adjust it to fit the footer's design. Next, I'll replace the "Powered by Starknet" text with "Onchain land, decentralized and secured" in the hero section.

- Update Community Links:
In the community section where the links are displayed, I'll add a Telegram link alongside other social media or community links. I'll use an icon  to represent Telegram appropriately.

- Create a "Guides" Page:
I'll create a new page component titled "Guides" with relevant content for tutorials or guides. Then, I'll add a link to this page in the site's navigation or footer, depending on the design.

- Add Light/Dark Mode Toggle:
Using JavaScript or React state, I'll create a toggle button that allows users to switch between light and dark mode. I'll ensure the website's CSS has both light and dark theme styles defined. Finally, I'll update the page to dynamically switch classes or styles based on the user's choice, and save the preference in localStorage to persist the setting.

By following these steps, I'll successfully reposition the "Powered by Starknet" text, update the community links, create a Guides page, and add a light/dark mode toggle to enhance the user experience of my landing page.

**Comment by abdegenius** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a fullstack developer worked with various frontend frameworks over the years as well as backend frameworks. currently transitioning into the web3 space.

### How I plan on tackling this issue
I will work with the current framework language and library to deliver this task.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer i would love to work on this issue 
Pleasee kindly assign :)

### How I plan on tackling this issue
please i would love to work on this issue

**Comment by SudiptaPaul-31** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hi, I’m Sudipta Paul, a full-stack developer with 1.5 years of experience in blockchain and web development. I’d like to contribute to this issue and improve the landing page design.

### How I plan on tackling this issue
My approach of solving this issue:

Move this element from the hero section to the footer. Replace it with the text “Onchain land, decentralized and secured” in the hero section.

Add the Telegram link to the existing community links and create a new Guides page that will link from the footer or the community section.

Adding  a toggle button for light/dark mode and using css variables or a preferred theme-management system to switch between modes, ensuring proper contrast and readability.

Ensure the light/dark mode works across devices and browsers, maintaining visual comfort for users in various lighting conditions.

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.


### How I plan on tackling this issue
i will Ensure accessibility compliance,
Use responsive design,
Test theme toggle functionality.

**Comment by DanielEmmanuel1** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Good day, my name is Deon and I’m a Full-Stack web3 developer with a strong passion for creating intuitive and user-friendly interfaces. 

I have experience in writing Typescript as well as modern JavaScript and its frameworks and a keen eye for design, which allows me to effectively translate design concepts into functional web applications. 

I’m dedicated to enhancing user experiences and continuously learning about best practices in frontend development.

### How I plan on tackling this issue
How I Plan to Solve The “Reposition "Powered by Starknet" to the Footer” Issue

-Firstly i will Identify the current placement of the "Powered by Starknet" text in the hero section of the landing page. This will likely be in the main hero component or within the landing page template.

-Next up I’ll transfer the "Powered by Starknet" text from the hero section to the footer and ensure it aligns well with the existing footer content and maintains visual consistency.

-I will then adjust the design to ensure it fits naturally within the footer. This may include modifying the font size, color, or padding to match the footer's overall style.


How I Plan to Solve The “Update the Hero Section” part of the Issue

- Firstly I will replace the "Powered by Starknet" text which was removed, and replace it with the new phrase: "Onchain land, decentralized and secured."  In the hero section.

- Ensure Alignment: Confirm that the new text is positioned properly and doesn’t interfere with other elements in the hero section. Ensure it blends with the visual design of the hero.


How i plan to Solve The “Update Community Links” part of the issue

- Add Telegram Link: I will Identify where the current community links like Twitter, Discord are located, and add the Telegram link alongside these, and ensure it follows the same styling and design principles.

- Check Accessibility: I’ll ensure that the link is easily accessible and works properly across both mobile and desktop devices.


How I Plan To Solve The “Create a Dedicated "Guides" Page” Part

- Set Up New Page: I will create a new "Guides" page that will serve as a resource hub. Add it to the navigation menu or footer where appropriate.

- Organize Content: I will structure this page to hold future guide-related content, like tutorials, FAQs, or user documentation. For now, a placeholder or basic content structure will suffice, but ensure the page follows the same styling as the rest of the site.


How I Plan To Implement Dark Mode
- I will introduce a toggle switch, button or probably a cool looking icon on the landing page to allow users to switch between light and dark mode. Place this toggle button in a visible and intuitive location, such as the header or Nav bar.

- After that is done I will begin implementing the functionality so that the page’s appearance dynamically adjusts between light and dark mode without requiring a page refresh and implement smooth transitions for a better user experience.

- I’ll make sure that the dark mode color scheme offers high contrast and is comfortable for users in low-light environments. Review all sections of the landing page (text, buttons, background, etc.) to ensure readability and usability.

- Finally I will test the changes (especially dark mode) across different browsers (Chrome, Firefox, Safari, etc.) to ensure compatibility and make sure it is responsive across multiple device screens

I believe with all the steps i listed above, i can efficiently solve all of the UI discrepancies within the project's codebase, I'm excited to contibute to Landver and can't wait to start. Do have a great day.

**Comment by Cyberking99** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
My name is Kingsley Kefas, I am a software engineer. With my 5+ years of experience as a software engineer and expertise in ReactJs and NextJs, I can easily handle the frontend restructuring and functionality implementation. I will ensure that the light/dark mode switch is smooth, user-friendly, and responsive while enhancing the overall user experience with attention to both functionality and design.

### How I plan on tackling this issue
First, I will locate the "Powered by Starknet" element in the current hero section (components/Hero.tsx) of the landing page and insert it into the footer component (components/Footer.tsx) to ensure consistency across all pages; then I will replace the original "Powered by Starknet" text in the hero section with the new text: "Onchain land, decentralized and secured". The new text will be styled properly to fit the design aesthetics of the hero section.
I will then add the Telegram link to the existing community links.

Secondly, I will create a new page for "Guides" and populate the page with any existing guides or placeholder content for future updates.

Next, I will implement a light/dark mode toggle button at the top navigation bar, then use useContext to track the user's theme preference. I will then store the user's theme preference (light or dark) in localStorage, so it persists across page reloads and sessions. In addition to this, I will leverage CSS variables/styled-components for smooth theme transitions.

**Comment by JoelVR17** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
**Update Footer and Community Links and Implement Dark Mode on Landing Page**

Hello LandVer team,

I am Joel Vargas, and I'm a member of Dojo Coding. I also come from OnlyDust.

I would like to request the assignment of this issue. Below is my proposed approach for implementing this issue:

### How I plan on tackling this issue
### Proposal to Reposition "Powered by Starknet", Update Community Links, and Add Light/Dark Mode Toggle

#### Problem
The "Powered by Starknet" element is currently placed in the hero section, which could be better positioned to enhance design aesthetics. Additionally, the community links need an update to include the Telegram link, and a "Guides" page should be created for easier access to resources. Lastly, there is no option for users to toggle between light and dark modes, limiting personalization and accessibility for users in different lighting conditions.

#### Solution

1. **Reposition "Powered by Starknet":**
   - Move the "Powered by Starknet" element from the hero section to the footer for better visual balance and to declutter the hero area.
   - Replace the hero section text with:  
     **"Onchain land, decentralized and secured."**

2. **Update Community Links:**
   - Add the **Telegram link** to the community section for easier communication and community building.
   - Ensure the link follows the same style as the existing community links (e.g., Twitter, Discord).

3. **Create a "Guides" Page:**
   - Introduce a new dedicated "Guides" page where users can find resources on how to get started, use the platform, and understand the project better.
   - Link to this page should be added to the main navigation bar or community section.

4. **Add Light/Dark Mode Toggle:**
   - Provide users with the ability to switch between light and dark modes on the landing page via a toggle or button.
   - The theme should dynamically adjust based on user selection, enhancing readability and ensuring visual comfort in different lighting conditions.

#### Implementation Details

1. **Move "Powered by Starknet" to Footer:**
   - Move the "Powered by Starknet" element to the footer and ensure it is styled consistently with the rest of the footer items.
   - Update the hero section to reflect the new text:
     ```html
     <p>Onchain land, decentralized and secured.</p>
     ```

2. **Add Telegram Link to Community Section:**
   - Add a new link for Telegram in the community links section:
     ```html
     <a href="https://t.me/YourTelegramLink" target="_blank">Telegram</a>
     ```
   - Ensure it matches the visual style and format of the existing links.

3. **Create a "Guides" Page:**
   - Add a new `Guides` page with relevant content.
   - Update the navigation bar to link to the new "Guides" page:
     ```html
     <a href="/guides">Guides</a>
     ```

4. **Implement Light/Dark Mode Toggle:**
   - Add a toggle switch to the landing page to allow users to switch between light and dark modes:
     ```jsx
     <ToggleThemeButton />
     ```

   - Implement logic to store the user’s preference (e.g., using `localStorage`):
     ```javascript
     const toggleTheme = () => {
       const newTheme = theme === 'light' ? 'dark' : 'light';
       document.documentElement.setAttribute('data-theme', newTheme);
       localStorage.setItem('theme', newTheme);
     };
     ```

   - Ensure CSS variables adjust dynamically between the two themes:
     ```css
     [data-theme='light'] {
       --background-color: #ffffff;
       --text-color: #000000;
     }

     [data-theme='dark'] {
       --background-color: #1a1a1a;
       --text-color: #f0f0f0;
     }
     ```

#### Definition of Completion

- **Repositioned "Powered by Starknet":** The "Powered by Starknet" element has been successfully moved from the hero section to the footer.
- **Updated Community Links:** The Telegram link is now included in the community links section.
- **New "Guides" Page:** A dedicated "Guides" page is created, accessible from the navigation bar or community section.
- **Light/Dark Mode Toggle:** A toggle or button is available on the landing page to switch between light and dark modes. The page's appearance adjusts accordingly, ensuring proper readability and visual comfort for all users.

#### Reference
- **Landing Page URL:** [Landver](https://landver.vercel.app/)
- **GitHub Repository:** [Landver Repo](https://github.com/NoshonNetworks/landver/tree/main/frontend/landing_page)

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hello @fishonamos I'm a front-end and a blockchain developer and will love to work on this

**Comment by sanieni6** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
hi there, I am Luis a front-end developer with 2 years of experience, I will be glad to contribute to this project my man.

### How I plan on tackling this issue
following your guidelines, this is my approach to solve this issue:
1. Refactor the "Powered by starknet" to "Onchain land, decentralized and secure" and move it to the footer 
2. Include telegram link in the community links
3. Create a "guides" page
4. Add a toggle buttom to switch between light and dark mode.

**Comment by Ayoazeez26** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a software developer with 6 years experience building applications

### How I plan on tackling this issue
Implement changes to the footer as described above
Implement dark mode and a toggle to make users choose what mode they prefer

**Comment by dimka90** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
i am a ceritfied full stack developer with half a decade years of experience of experience currently learning blockchain and web3 at blockfuse labs

### How I plan on tackling this issue

This are the steps i will take to fix the problem
1. Move "Powered by Starknet" to Footer
Find and move the "Powered by Starknet" element from the hero section to the footer.
Replace it with the text: "Onchain land, decentralized and secured."
2. Add Telegram Link
In the community links section, add the Telegram link alongside existing social media links.
3. Create a "Guides" Page
Add a new page for "Guides" and link it from the navigation bar or footer.
4. Implement Dark Mode
Add a toggle button to switch between light and dark modes.
Use JavaScript to toggle dark mode and CSS variables for light/dark styles.
Store user preferences in localStorage to remember their choice.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
To update the footer and community links and implement dark mode on the landing page, I will first move the "Powered by Starknet" text from the hero section to the footer. In its place, I will add the message "Onchain land, decentralized and secured." I will also update the community links by including a Telegram link and creating a dedicated "Guides" page to provide users with helpful resources.

Next, I will implement a toggle button on the landing page that allows users to switch between light and dark modes. This feature will enhance the user experience by accommodating different lighting preferences. I will ensure that when the mode is switched, the page's appearance adjusts to maintain readability and visual comfort.

To complete this task, I will test the functionality of the toggle and make sure the layout is visually appealing in both modes. The work will be considered done when users can easily switch between light and dark modes and the footer and community links are updated according to the specifications.

**Comment by Mystic-Nayy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a web3 developer, I have expertise in smart contracts, decentralized technologies, and frameworks like React. I can build innovative dApps, contribute to open-source projects, educate others, and network with industry leaders to advance my career in the decentralized space.

ETA = 3 Working days

### How I plan on tackling this issue
To complete the task:

1. **Reposition "Powered by Starknet"**: Move it to the footer and replace the hero section text with "Onchain land, decentralized and secured."
2. **Update Community Links**: Add the Telegram link to the community section and create a "Guides" page.
3. **Light/Dark Mode Toggle**: Implement a toggle button for switching between light and dark modes, ensuring the landing page adapts accordingly for a better user experience.

**Comment by jsandinoDev** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I'm a full-stack developer with web3 experience, specializing in smart contracts and decentralized applications. I've worked on projects using React, Solidity, Cairo, and blockchain tools. My skills in both front-end and back-end development allow me to build scalable and secure solutions for web3 ecosystems.

### How I plan on tackling this issue
. Reposition "Powered by Starknet"
Locate the "Powered by Starknet" text in the hero section of the code.
Move it to the Footer component and update its styling if necessary.
Replace the text in the Hero section with: "Onchain land, decentralized and secured."
2. Update Community Links
Add Telegram link to the existing community links (e.g., Twitter, GitHub).
Ensure the new link opens in a new tab for external navigation.
3. Create a "Guides" Page
Create a new "Guides" page with relevant content.
Add a link to the page in the navigation or footer for easy access.
4. Implement Dark Mode Toggle
Add a toggle button for switching between light and dark modes.
Use state management (e.g., React’s useState) to track the selected mode.
Apply dark mode styles using TailwindCSS or custom CSS (body.dark-mode).
Persist preference using localStorage to remember the user’s mode.
5. Testing
Ensure the text update, dark mode toggle, and links work as expected across devices.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I'm a Full Stack Blockchain Developer with demonstrable expertise across modern web and blockchain technologies. My tech stack centers on Next.js, TypeScript, React, and Node.js for web development, complemented by Three.js for 3D experiences, and Solidity/Rust for blockchain solutions. 

What sets me apart is my proven track record on OnlyDust, where I've made 83 significant contributions across 15 different projects since Edition 1. This extensive involvement reflects my ability to deliver quality solutions under tight deadlines while adapting to diverse project requirements.  

With my deep experience in hackathon environments, I bring both technical excellence and practical development skills to the table. I'm confident I can contribute meaningfully to pushing the boundaries of what's possible in blockchain development while maintaining a focus on user-centric solutions. 

  

My profile (https://app.onlydust.com/u/Ugo-X) showcases my consistent ability to deliver results across various blockchain challenges. I'm excited to bring this experience and drive for innovation to your team. 

### How I plan on tackling this issue
Move "Powered by Starknet" to Footer: I will relocate the "Powered by Starknet" text from the hero section to the footer. Then, I’ll modify the hero section to display the message "Onchain land, decentralized and secured." This will involve a simple adjustment to the HTML structure within the landing page component.  
Update Community Links: I’ll add the Telegram link to the existing community links. Since these links are likely located in a dedicated section or component, I’ll follow the same structure when adding the new link for consistency. I'll ensure all the links are visible and functional, using Tailwind CSS for styling to align with the page’s design.  
Create "Guides" Page: I’ll develop a new page under the /guides route, which will serve as a hub for how-to content. I’ll configure the basic routing in the Next.js project and ensure it integrates smoothly with the current navigation system.  
Implement Dark Mode: I’ll introduce a dark mode toggle in the form of a button or switch on the landing page. The theme state will be managed using local storage to retain the user's preference across sessions. I’ll use Tailwind CSS to define both light and dark themes, ensuring smooth transitions. The focus will be on maintaining readability, contrast, and visual comfort in both modes.  
Testing and Validation: After completing these changes, I’ll test the layout’s responsiveness, check the functionality of the community links, and ensure that dark mode does not compromise accessibility or user experience. Additionally, I’ll verify that dark mode preferences persist between page reloads.  
Expected delivery timeline: 2-3 days.

**Comment by KevinLatino** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I have a deep passion for Web3 and I am currently working as a frontend developer intern at a Web2 company, focusing on Next.js. Additionally, I am an active member of Dojo Coding, a prominent Web3 community in LATAM, which has given me great exposure to decentralized technologies.

Recently, I have been working on a project for Base LATAM's Buildathon, where I am gaining hands-on experience in building decentralized applications. I am eager to continue growing and contributing, and see this as a fantastic opportunity to further develop my skills and make a significant impact.

This is my first OD Hack, so I will appreciate it if you give me the chance to contribute to this amazing project.

Some frontend projects that i have:
https://buildmyevent.xyz/
https://peritazgo-website.vercel.app/



### How I plan on tackling this issue
To address the requested changes effectively, I would follow these steps:

Reposition the "Powered by Starknet" Element: I would move the "Powered by Starknet" text from the hero section to the footer of the website. This adjustment not only declutters the hero area but also maintains the visibility of the Starknet branding in a more subtle way. In its place, I would insert the text "Onchain land, decentralized and secured," emphasizing the core values of the platform.

Update Community Links: I would enhance the community links section by adding a Telegram link. This addition will facilitate better communication with the community and provide users with more ways to engage. I would ensure that the new link is clearly visible and integrated seamlessly with the existing community links for consistency.

Create a Dedicated "Guides" Page: To improve user onboarding and support, I would create a dedicated "Guides" page. This page will house all relevant tutorials and documentation, making it easier for users to access essential information. I would ensure the design is user-friendly, allowing for easy navigation and quick access to guides.

Implement Light and Dark Mode Toggle: I would introduce a toggle or button on the landing page to allow users to switch between light and dark modes. This feature would enhance user experience by accommodating different preferences and ensuring readability in various lighting conditions. I would implement a responsive design that smoothly transitions the page’s appearance according to the selected mode.

Definition of Completion: To mark the task as complete, I would ensure that the toggle is functional, allowing users to switch modes seamlessly, and that the overall appearance of the landing page adjusts accordingly for optimal readability and visual comfort.                                                                                             
@fishonamos  I hope you give me the opportunity to contribute to this amazing project; I would be very grateful.

**Comment by Eche5** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a full stack developer with over a year if experience and my skill in frontend development will be leveraged to implement these changes while maintaining a user-friendly experience.

### How I plan on tackling this issue
I will Locate the current position of the "Powered by Starknet" element in the hero section within the codebase. Then I'll move the element to the footer section, ensuring it retains proper styling and alignment consistent with the footer's design. Replace the hero text with "Onchain land, decentralized and secured." And also include the Telegram link in the community links and create a dedicated "Guides" page.

**Comment by Dprof-in-tech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hello, I'm Dprof-in-tech, a seasoned Full Stack Blockchain Developer, and I'm excited to be part of ODHACK 9! I have a strong foundation in technologies such as Next.js, TypeScript, JavaScript, React, Node.js, Rust, and Cairo, I've built extensive experience across the blockchain development landscape.

I first got involved with OnlyDust during Edition 2, and since then, I've made 39 contributions across 11 different projects. Working on the platform has really helped me sharpen my skills, especially when it comes to delivering great solutions under tight deadlines. I love combining technical know-how with a user-focused approach, whether it's building immersive 3D experiences or crafting smart contracts that solve real-world problems.

Throughout, I've consistently demonstrated the ability to adapt and contribute effectively to diverse challenges. I'm confident in my ability to tackle new problems and drive innovation within the blockchain space. As we kick off ODHACK 9, I'm eager to apply my previous experience and technical expertise to push the boundaries of what's possible.

You can view my public profile on OnlyDust here: https://app.onlydust.com/u/Dprof-in-tech


### How I plan on tackling this issue
Approach for Issue #92: Update Footer and Community Links and Implement Dark Mode

Move "Powered by Starknet" to Footer:

 I’ll start by repositioning the "Powered by Starknet" text from the hero section to the footer. I'll then update the hero section to display "Onchain land, decentralized and secured." This will be a straightforward adjustment to the HTML structure within the landing page component.

Update Community Links: I’ll include the Telegram link in the existing community links. Since the links are likely stored in a dedicated section or component, I’ll add the new link following the same structure for consistency. I’ll ensure all links are visible and functional, possibly using Tailwind CSS for styling to match the page's design.

Create "Guides" Page: I’ll build out a new page under the /guides route. This page will serve as a central hub for any how-to content. I’ll set up the basic routing in the Next.js project and ensure it integrates seamlessly with the current navigation.


Implement Dark Mode: For the dark mode toggle, I’ll introduce a button or switch on the landing page. I’ll handle the theme state using local storage to remember the user’s preference across sessions. I'll use Tailwind CSS to define both light and dark themes and ensure smooth transitions. The key here will be maintaining readability and contrast, ensuring visual comfort regardless of the mode.

Testing and Validation: Once the changes are complete, I’ll test the responsiveness of the layout, check that the community links function correctly, and ensure the dark mode implementation does not affect accessibility or user experience. I’ll also verify the persistence of dark mode preferences between page reloads.

Expected delivery timeline - 2-3 days.

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hello, i'm a frontend and blockchain developer, i will love to work on this issue

### How I plan on tackling this issue
- I will "Powered by Starknet" to Footer
-i will update the hero text
- i will  add the Telegram Link
- I will create a "Guides" Page

**Comment by sasasamaes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Full Stack developer with 5+ years of experience involved in the full software development lifecycle. My experience includes providing IT solutions for enterprises using JavaScript, React, TypeScript, Node.js, and MongoDB. Additionally, I am expanding my knowledge in Web3 technologies, particularly in Cairo and Solidity.

I am also a community leader and sensei at Dev.f, where I mentor and lead a vibrant community of developers and am a Dojo Coding Member.

My areas of interest include Web3, frontend, backend, and full-stack development.

### How I plan on tackling this issue
Could you please work on this issue and apply the changes as indicated in the description

**Comment by Noble14477** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I have over three years of experience in web development, specializing in technologies such as HTML, CSS, JavaScript, and React. This experience has provided me with a strong foundation in front-end development, allowing me to create intuitive user interfaces. Additionally, my background in graphic design has honed my ability to understand user experience and aesthetics, which is crucial in crafting visually appealing and user-friendly applications.

My experience with JavaScript also extends to backend technologies, where I've worked on RESTful APIs and managed database interactions. This understanding of both front-end and back-end development enables me to approach tasks holistically, ensuring smooth integration between components.

### How I plan on tackling this issue
Firstly, i would Open the hero section in your project files.
then, Cut the "Powered by Starknet" element and paste it into the footer component. Ensure it retains its styling and functionality.
then, In the hero section, replace the moved element with the text "Onchain land, decentralized and secured." Adjust any necessary styles to ensure it fits well within the hero section.

Next, Find the component responsible for rendering community links.
Insert the Telegram link into the community links list. Make sure it follows the same styling and format as existing links.

Next, In the routing setup, create a new route for the "Guides" page
Populate the page with relevant content, such as resources or tutorials related to the project. Ensure that it has a consistent design with the rest of the site.

Next,  Create a toggle switch or button component for light/dark mode, which can be placed in the header or as part of the hero section.
Will use for eg. React's state management to handle the current mode. You might want to use a context or a global state management library (like Redux) if the theme needs to be accessible across multiple components.
then, Define CSS classes for both light and dark modes. Use conditional rendering to apply the appropriate class based on the current mode

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
i have proper frontend experience, and looking forward to contribute to this repo

### How I plan on tackling this issue
i would follow exactly what is mentioned and give you apt results.
